name: Test Workflow

on:
  push:
    branches:
      - main

jobs:
  npm-publish:
    name: npm-publish
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install
        run: npm ci

      - name: Generate Release
        run: |
          git config user.email "hi@inkasadev.com"
          git config user.name "inks2d Bot"
          git config advice.ignoredHook false
          node scripts/create_release_inks2d.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
